dataset: FashionMNIST
data_dir: ./data
batch_size: 128
epochs: 10
lr: 0.001
weight_decay: 0.0001
seed: 42
num_workers: 2
val_split: 5000
default_dropout: 0.2
default_subset_size: 10000
log_interval: 50
